# Generated by Django 5.2.7 on 2025-10-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('On-time', 'On-time'), ('Delayed', 'Delayed'), ('Cancelled', 'Cancelled')], default='On-time', max_length=20),
        ),
    ]
